### ISSUE TITLE
allow _clang-format along .clang-format as config file name

### ISSUE THREAD

**Issue by paroj** [wangzw/CppStyle#12]
to be consistent with clang-format

**Comment by schulmar** [comment]
I second this.
Additionally, I find _clang-format files to be more conveniently editable (from within Eclipse):
They are visible by default in Eclipse's Project Explorer as opposed to .clang-format files.

**Comment by wangzw** [comment]
Reasonable requirement. I will add this feature later.

**Comment by AndiDog** [comment]
Instead of having the plugin find the style file, just pass `-style=file` to clang-format. Then also `-fallback-style=none` should be passed which ensures that no reformatting is done in case no such file is found in the parent directories. You should make this configurable so that people can still define a fallback style if they want to ("Google" is currently the default in your code, which cannot be configured at the moment).
