### ISSUE TITLE
Manual Build and setup Instructions

### ISSUE THREAD

**Issue by pashnidgunde** [wangzw/CppStyle#18]
Please provide manual setup instructions. It would be great if a jar file is attached to the website with manual setup instructions. This is required because sometimes, due to firewall restrictions, it could be difficult to connect to marketplace to get this plugin.

For example, moonrise theme for eclipse has manual setup instructions on git as ::

http://guari.github.io/eclipse-ui-theme/

**Comment by escrowdis** [comment]
Same problem, need help

**Comment by aabusair** [comment]
Guys any updates on this ? trying couple of things but no luck...

**Comment by wangzw** [comment]
https://github.com/wangzw/CppStyle/blob/master/README.md#manual

**Comment by aabusair** [comment]
Wang,
Tried doing that but got lots of errors. Appreciate if you can run maven clean package and post the file.

Thanks

**Comment by wangzw** [comment]
You can always install the latest version from update site ```http://www.cppstyle.com/update```
Let me know if you get any trouble.

**Comment by aabusair** [comment]
the link above won't allow me to download ( I have to use within eclipse which i can't access from my company due to security restriction). So i downloaded the latest version from gitHub then unzip and tried to run "mvn clean package' ........but got lots of errors:

[ERROR] C:\Users\Amr\Downloads\CppStyle-oxygen\plugin\src\org\wangzw\plugin\cppstyle\ClangFormatFormatter.java:[367]
[ERROR]         String clangFormat = getClangFormatPath();
[ERROR]         ^^^^^^
[ERROR] String cannot be resolved to a type
[ERROR] C:\Users\Amr\Downloads\CppStyle-oxygen\plugin\src\org\wangzw\plugin\cppstyle\ClangFormatFormatter.java:[389]
[ERROR]         public static String getClangFormatPath() {
[ERROR]                       ^^^^^^
[ERROR] String cannot be resolved to a type
[ERROR] C:\Users\Amr\Downloads\CppStyle-oxygen\plugin\src\org\wangzw\plugin\cppstyle\ClangFormatFormatter.java:[390]
[ERROR]         return CppStyle.getDefault().getPreferenceStore().getString(CppStyleConstants.CLANG_FORMAT_PATH);
[ERROR]                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] String cannot be resolved to a type
[ERROR] 708 problems (708 errors)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]

**Comment by wangzw** [comment]
All update site is on Github pages, that means you can checkout branch ```gh-pages``` and use ```file:///<code_path>/update/``` as local update site. 

https://github.com/wangzw/CppStyle/tree/gh-pages

But if you have limited network access, you may still fail to install CppStye since its dependencies need to be downloaded from CDT update site.

**Comment by aabusair** [comment]
Thanks Wang ! let it give a try .........

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
